M48
; DRILL file {KiCad 9.0.2} date 2025-06-05T07:55:04-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-05T07:55:04-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X110.0Y-75.0
X110.0Y-95.0
X130.0Y-75.0
X130.0Y-95.0
M30
